#ifndef __SPRITES_H__
#define __SPRITES_H__

enum sprite {
  SPR_RANDOM_TRASH2 = 0,
  SPR_ITEM_TEST,
  SPR_PLAYER,
  SPR_PIXEL,
  SPR_MIRROR_ROOM,
  SPR_ROPE_ROOM,
  SPR_ROOM_TILESET,
  SPR_BOX_ITEM,
  SPR_BOX_TEST,
  SPR_LOCK,
  SPR_ROPE,
  SPR_ITEM_TEST2,
  SPR_DOOR,
  SPR_TRASH,
  SPR_PLAYER_TEST,
  SPR_DOOR_LOCKED,
  SPR_RANDOM_TRASH0,
  SPR_ROCK,
  SPR_MIRROR,
  SPR_RANDOM_TRASH1,
  SPR_BOX_TAPED,
  SPR_KEY,
  SPRITES_AMOUNT
};

#endif/*__SPRITES_H__*/
