#ifndef __SPRITES_H__
#define __SPRITES_H__

enum sprite {
  SPR_ITEM_TEST = 0,
  SPR_PLAYER,
  SPR_PIXEL,
  SPR_ROOM_TILESET,
  SPR_BOX_ITEM,
  SPR_BOX_TEST,
  SPR_LOCK,
  SPR_ROPE,
  SPR_ITEM_TEST2,
  SPR_DOOR,
  SPR_TRASH,
  SPR_PLAYER_TEST,
  SPR_DOOR_LOCKED,
  SPR_MIRROR,
  SPRITES_AMOUNT
};

#endif/*__SPRITES_H__*/
