# TODO: add scenes

[entity.unique.player]
component = [ "renderable" ]
exclude   = [ "color", "opacity", "texture_size" ]
field.wiggle_cur    = "float"
field.wiggle_target = "float"

[entity.some_entity]
component = [ "renderable" ]

[component.renderable]
position         = "struct v2"
scale            = "struct v2"
texture_position = "struct v2u"
texture_size     = "struct v2u"
pivot            = "struct v2"
angle            = "float"
color            = "struct color"
opacity          = "float"
depth            = "float"

