[entity.unique.player]
component = [ "renderable", "collidable" ]
exclude   = [ "color", "opacity", "flash" ]
field.direction     = "struct v2"
field.interact_pos  = "struct v2"
field.interact_rad  = "float"
field.wiggle_cur    = "float"
field.wiggle_target = "float"
field.item_held     = "int32_t"

# the 'box' entity type has to come before the 'item' one 
[entity.box]
component = [ "renderable", "collidable", "flashable" ]
exclude   = [ "scale", "origin", "angle", "color", "opacity" ]
field.item_held = "enum item_type"

[entity.item]
has_init = false
component = [ "renderable", "collidable", "flashable" ]
exclude   = [ "color", "opacity", "origin", "scale", "angle" ]
field.position_target = "struct v2"
field.launch_velocity = "struct v2"
field.next_position   = "struct v2"
field.type            = "enum item_type"

[entity.solid]
has_init   = false
has_update = false
component = [ "collidable" ]

[component.renderable]
position = "struct v2"
scale    = "struct v2"
sprite   = "enum sprite"
origin   = "struct v2"
angle    = "float"
color    = "struct color"
opacity  = "float"
depth    = "float"
flash    = "float"

[component.collidable]
position = "struct v2"
size     = "struct v2"

[component.flashable]
flash_target = "float"
flash        = "float"
