[entity.unique.player]
component = [ "renderable", "collidable" ]
exclude   = [ "color", "opacity", "origin" ]
field.direction     = "struct v2"
field.wiggle_cur    = "float"
field.wiggle_target = "float"
field.interact_rad  = "float"
field.held_item     = "int32_t"

[entity.item]
component = [ "renderable", "collidable" ]
exclude   = [ "color", "opacity", "origin", "scale", "angle" ]
field.position_target = "struct v2"

[component.renderable]
position         = "struct v2"
scale            = "struct v2"
texture_position = "struct v2u"
texture_size     = "struct v2u"
origin           = "struct v2"
angle            = "float"
color            = "struct color"
opacity          = "float"
depth            = "float"

[component.collidable]
position = "struct v2"
size     = "struct v2"
