# TODO: add scenes

[entity.unique.player]
component = [ "renderable" ]
exclude   = [ "color", "opacity", "size", "texture_size" ]

[entity.some_entity]
component = [ "renderable" ]

[component.renderable]
position         = "struct v2"
size             = "struct v2"
texture_position = "struct v2u"
texture_size     = "struct v2u"
angle            = "float"
color            = "struct color"
opacity          = "float"
depth            = "float"

